import base64
import hashlib
import struct
import zlib
from pathlib import Path

from filegrail.sources.c2pa import read_c2pa_manifest


def _box(box_type: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload) + 8) + box_type + payload


def _description(content_type: bytes, label: str) -> bytes:
    uuid = content_type + b"\x00\x11\x00\x10\x80\x00\x00\xaa\x008\x9bq"
    return _box(b"jumd", uuid + b"\x03" + label.encode() + b"\x00")


def _manifest(cbor_payload: bytes, assertions: tuple = ()) -> bytes:
    claim = _box(b"jumb", _description(b"c2cl", "c2pa.claim.v2") + _box(b"cbor", cbor_payload))
    body = _description(b"c2pa", "c2pa")
    if assertions:
        store = b"".join(
            _box(b"jumb", _description(b"c2as", label) + _box(b"cbor", payload))
            for label, payload in assertions
        )
        body += _box(b"jumb", _description(b"c2as", "c2pa.assertions") + store)
    return _box(b"jumb", body + claim)


def _cbor(value) -> bytes:
    """Encode the CBOR subset the tests need.

    Hand-written byte literals are encoded by their own length prefix, which is
    exactly the category of arithmetic a test should not be doing by hand.
    """

    def head(major: int, argument: int) -> bytes:
        if argument < 24:
            return bytes([major << 5 | argument])
        if argument < 0x100:
            return bytes([major << 5 | 24, argument])
        if argument < 0x10000:
            return bytes([major << 5 | 25]) + struct.pack(">H", argument)
        return bytes([major << 5 | 26]) + struct.pack(">I", argument)

    if isinstance(value, Tagged):
        return head(6, value.tag) + _cbor(value.value)
    if isinstance(value, Fixed):
        # Always four bytes, so patching the value cannot resize the manifest.
        return bytes([26]) + struct.pack(">I", value.value)
    if isinstance(value, bytes):
        return head(2, len(value)) + value
    if isinstance(value, str):
        raw = value.encode("utf-8")
        return head(3, len(raw)) + raw
    if isinstance(value, int):
        return head(0, value)
    if isinstance(value, list):
        return head(4, len(value)) + b"".join(_cbor(item) for item in value)
    if isinstance(value, dict):
        return head(5, len(value)) + b"".join(
            _cbor(key) + _cbor(item) for key, item in value.items()
        )
    raise TypeError(value)


class Fixed:
    """A CBOR integer pinned to one width, so a later patch cannot resize it."""

    def __init__(self, value: int) -> None:
        self.value = value


class Tagged:
    def __init__(self, tag: int, value) -> None:
        self.tag = tag
        self.value = value


IPTC = "http://cv.iptc.org/newscodes/digitalsourcetype/"

GENERATED_CLAIM = _cbor(
    {
        "claim_generator_info": {"name": "OpenAI Media Service API"},
        "actions": [
            {
                "action": "c2pa.created",
                "when": Tagged(0, "2026-07-15T00:00:00Z"),
                "softwareAgent": {"name": "gpt-image", "version": "2.0"},
                "digitalSourceType": IPTC + "trainedAlgorithmicMedia",
            }
        ],
    }
)


def _png_with(path: Path, jumbf: bytes) -> tuple[int, int]:
    def chunk(category: bytes, payload: bytes) -> bytes:
        return (
            struct.pack(">I", len(payload))
            + category
            + payload
            + struct.pack(">I", zlib.crc32(category + payload))
        )

    header = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0))
    manifest_chunk = chunk(b"caBX", jumbf)
    path.write_bytes(header + manifest_chunk + chunk(b"IDAT", b"\x00") + chunk(b"IEND", b""))
    return len(header), len(manifest_chunk)


def _svg_with(path: Path, jumbf: bytes) -> None:
    """A drawing carrying the same manifest store, written the way XML can."""
    payload = base64.b64encode(jumbf).decode()
    path.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" xmlns:c2pa="http://c2pa.org/manifest">'
        f"<metadata><c2pa:manifest>{payload}</c2pa:manifest></metadata>"
        '<path d="M0 0 L1 1"/></svg>',
        encoding="utf-8",
    )


def test_reads_a_manifest_an_svg_carries_as_base64(tmp_path: Path):
    drawing = tmp_path / "mark.svg"
    _svg_with(drawing, _manifest(GENERATED_CLAIM))

    record = read_c2pa_manifest(drawing)

    assert record is not None
    assert record.where == {"object": "c2pa:manifest element"}


def test_reads_an_ai_generated_png(tmp_path: Path):
    image = tmp_path / "generated.png"
    _png_with(image, _manifest(GENERATED_CLAIM))

    origin = read_c2pa_manifest(image)

    assert origin is not None
    assert origin.source == "c2pa"
    assert origin.tool == "OpenAI Media Service API (gpt-image 2.0)"
    assert origin.at == "2026-07-15T00:00:00Z"
    assert "generated by an AI model" in origin.note
    assert origin.priority == 60
    assert origin.fields == {
        "claim_generator": "OpenAI Media Service API",
        "softwareAgent": "gpt-image 2.0",
        "digitalSourceType": IPTC + "trainedAlgorithmicMedia",
        "actions": "c2pa.created",
    }


def test_always_says_the_signature_was_not_verified(tmp_path: Path):
    image = tmp_path / "generated.png"
    _png_with(image, _manifest(GENERATED_CLAIM))

    assert "signature not verified" in read_c2pa_manifest(image).note


def test_camera_capture_is_labelled_as_such(tmp_path: Path):
    claim = _cbor(
        {"actions": [{"action": "c2pa.created", "digitalSourceType": IPTC + "digitalCapture"}]}
    )
    image = tmp_path / "photo.png"
    _png_with(image, _manifest(claim))

    assert "captured by a camera" in read_c2pa_manifest(image).note


def test_png_without_a_manifest(tmp_path: Path):
    image = tmp_path / "plain.png"
    _png_with(image, b"")
    image.write_bytes(image.read_bytes().replace(b"caBX", b"tEXt"))

    assert read_c2pa_manifest(image) is None


def test_unsupported_suffix_is_skipped(tmp_path: Path):
    document = tmp_path / "notes.txt"
    document.write_text("hello", encoding="utf-8")

    assert read_c2pa_manifest(document) is None


def test_corrupt_manifest_is_not_an_error(tmp_path: Path):
    image = tmp_path / "broken.png"
    _png_with(image, b"\x00\x00\x00\x10jumb" + b"\xff" * 8)

    assert read_c2pa_manifest(image) is None


def test_truncated_box_length_does_not_hang(tmp_path: Path):
    image = tmp_path / "bad-length.png"
    _png_with(image, struct.pack(">I", 0xFFFFFF) + b"jumb" + b"\x00" * 4)

    assert read_c2pa_manifest(image) is None


#: A value that will not occur by accident in the rest of the fixture, so the
#: real digest can be patched in exactly where the placeholder sat.
_PLACEHOLDER = b"\xab" * 32


def _png_with_binding(path: Path, claim: bytes, *, alg: str | None = "sha256") -> None:
    """Write a PNG whose data hash assertion really does cover its own bytes.

    The assertion has to name the range it excludes, and that range is only
    known once the file has been laid out - so the manifest is written twice.
    The exclusion values are pinned to a fixed width and the digest is written
    over a placeholder of its own length, which is what keeps the second pass
    from moving anything the first pass measured.
    """

    def build(start: int, length: int) -> bytes:
        fields = {"exclusions": [{"start": Fixed(start), "length": Fixed(length)}]}
        if alg is not None:
            fields["alg"] = alg
        fields["hash"] = _PLACEHOLDER
        assertion = _cbor(fields)
        return _manifest(claim, (("c2pa.hash.data", assertion),))

    start, length = _png_with(path, build(0, 0))
    _png_with(path, build(start, length))

    raw = bytearray(path.read_bytes())
    digest = hashlib.sha256(bytes(raw[:start]) + bytes(raw[start + length :])).digest()
    at = raw.index(_PLACEHOLDER)
    raw[at : at + len(_PLACEHOLDER)] = digest
    path.write_bytes(bytes(raw))


def test_a_hash_binding_that_matches_the_file_is_reported(tmp_path: Path):
    image = tmp_path / "bound.png"
    _png_with_binding(image, GENERATED_CLAIM)

    assert "hash binding matches" in read_c2pa_manifest(image).note


def test_a_hash_binding_that_does_not_match_the_file_is_reported(tmp_path: Path):
    """The point of the check: a manifest that is not about these bytes."""
    image = tmp_path / "transplanted.png"
    _png_with_binding(image, GENERATED_CLAIM)

    raw = bytearray(image.read_bytes())
    raw[-1] ^= 0xFF  # a byte outside the excluded manifest chunk
    image.write_bytes(bytes(raw))

    assert "hash binding does not match" in read_c2pa_manifest(image).note


def test_a_manifest_without_a_hash_assertion_claims_nothing_about_binding(tmp_path: Path):
    image = tmp_path / "unbound.png"
    _png_with(image, _manifest(GENERATED_CLAIM))

    assert "hash binding" not in read_c2pa_manifest(image).note


def test_a_hash_algorithm_this_cannot_compute_is_not_guessed_at(tmp_path: Path):
    image = tmp_path / "exotic.png"
    _png_with_binding(image, GENERATED_CLAIM, alg="whirlpool")

    assert "hash binding" not in read_c2pa_manifest(image).note


def test_the_hash_algorithm_may_be_inherited_from_the_claim(tmp_path: Path):
    """The specification makes `alg` optional in the assertion when the claim
    already states one, and real manifests leave it out."""
    claim = _cbor(
        {
            "alg": "sha256",
            "claim_generator_info": {"name": "Quiet Tool"},
            "actions": [{"action": "c2pa.created"}],
        }
    )
    image = tmp_path / "inherited.png"
    _png_with_binding(image, claim, alg=None)

    assert "hash binding matches" in read_c2pa_manifest(image).note


def test_a_manifest_that_is_not_decodable_cbor_does_not_end_the_scan(tmp_path: Path):
    """One crafted file must not take the run down with it.

    `_walk` catches the decoder's own error and carries on, which is what makes
    a malformed manifest ordinary here rather than fatal. An exception of any
    other type walks straight past that clause, out of `read_c2pa_manifest` and
    out of the scan - a hundred-byte file denying the whole tool.
    """
    image = tmp_path / "crafted.png"
    _png_with(image, _manifest(b"\x5f\x00\xff"))

    assert read_c2pa_manifest(image) is None


def _store(*manifests: bytes) -> bytes:
    return _box(b"jumb", _description(b"c2pa", "c2pa") + b"".join(manifests))


def _manifest_box(urn: str, claim: bytes, assertions: tuple = ()) -> bytes:
    store = b"".join(
        _box(b"jumb", _description(b"c2as", label) + _box(b"cbor", payload))
        for label, payload in assertions
    )
    body = _description(b"c2ma", urn)
    if store:
        body += _box(b"jumb", _description(b"c2as", "c2pa.assertions") + store)
    body += _box(b"jumb", _description(b"c2cl", "c2pa.claim.v2") + _box(b"cbor", claim))
    return _box(b"jumb", body)


def test_active_manifest_lists_its_actions_and_ingredients(tmp_path: Path):
    """The last manifest in the store describes the file; the earlier one is
    the history of the ingredient it was edited from."""
    original = _manifest_box(
        "urn:uuid:1111", _cbor({"claim_generator_info": {"name": "Camera Firmware"}})
    )
    actions = _cbor(
        {
            "actions": [
                {"action": "c2pa.opened", "when": Tagged(0, "2026-08-01T10:00:00Z")},
                {"action": "c2pa.color_adjustments"},
                {"action": "c2pa.resized"},
            ]
        }
    )
    parent = _cbor(
        {
            "title": "IMG_0001.jpg",
            "format": "image/jpeg",
            "relationship": "parentOf",
            "document_id": "xmp.did:1111",
            "c2pa_manifest": {"url": "self#jumbf=/c2pa/urn:uuid:1111", "hash": b"\x00"},
        }
    )
    component = _cbor({"title": "logo.png", "relationship": "componentOf"})
    edited = _manifest_box(
        "urn:uuid:2222",
        _cbor({"claim_generator_info": {"name": "Photo Editor", "version": "9.1"}}),
        (
            ("c2pa.actions.v2", actions),
            ("c2pa.ingredient.v2", parent),
            ("c2pa.ingredient.v2__1", component),
        ),
    )
    image = tmp_path / "edited.png"
    _png_with(image, _store(original, edited))

    found = read_c2pa_manifest(image)

    assert found is not None
    assert found.tool == "Photo Editor 9.1"
    assert found.at == "2026-08-01T10:00:00Z"
    assert found.note == "derived from IMG_0001.jpg; 2 manifests; signature not verified"
    assert found.fields["actions"] == "c2pa.opened, c2pa.color_adjustments, c2pa.resized"
    assert found.fields["manifests"] == "2"
    assert found.fields["ingredients"] == "2"
    assert found.fields["Ingredient[1]:title"] == "IMG_0001.jpg"
    assert found.fields["Ingredient[1]:relationship"] == "parentOf"
    assert found.fields["Ingredient[1]:documentID"] == "xmp.did:1111"
    assert found.fields["Ingredient[1]:manifest"] == "own manifest"
    assert found.fields["Ingredient[2]:title"] == "logo.png"
    assert "Ingredient[2]:manifest" not in found.fields


# --- the other containers ---------------------------------------------------
#
# The same JUMBF, carried the way each container carries it: a TIFF tag, a RIFF
# chunk, a uuid box, an ID3 frame. Each layout is the one c2pa-rs writes.


def _tiff_with(path: Path, jumbf: bytes) -> None:
    """Tag 52545, typed UNDEFINED, in the first IFD."""
    base = 8 + 2 + 12 + 4
    path.write_bytes(
        b"MM\x00\x2a"
        + struct.pack(">I", 8)
        + struct.pack(">H", 1)
        + struct.pack(">HHII", 0xCD41, 7, len(jumbf), base)
        + struct.pack(">I", 0)
        + jumbf
    )


def _wav_with(path: Path, jumbf: bytes) -> None:
    """A `C2PA` chunk at the top level of the RIFF, after the format chunk."""
    fmt = b"fmt " + struct.pack("<I", 16) + struct.pack("<HHIIHH", 1, 1, 8000, 16000, 2, 16)
    manifest = (
        b"C2PA" + struct.pack("<I", len(jumbf)) + jumbf + (b"\x00" if len(jumbf) % 2 else b"")
    )
    body = b"WAVE" + fmt + manifest
    path.write_bytes(b"RIFF" + struct.pack("<I", len(body)) + body)


def _mp4_with(path: Path, jumbf: bytes) -> None:
    """A `uuid` box with the C2PA uuid: version and flags, a purpose, an offset, the store."""
    uuid = bytes.fromhex("d8fec3d61b0e483c92975828877ec481")
    payload = uuid + b"\x00\x00\x00\x00" + b"manifest\x00" + struct.pack(">Q", 0) + jumbf
    path.write_bytes(_box(b"ftyp", b"isom\x00\x00\x02\x00isom") + _box(b"uuid", payload))


def _mp3_with(path: Path, jumbf: bytes) -> None:
    """A GEOB frame whose object is the manifest store, in an ID3v2.4 tag."""
    mime = b"application/x-c2pa-manifest-store\x00"
    body = b"\x00" + mime + b"c2pa\x00" + b"c2pa\x00" + jumbf
    size = len(body)
    synchsafe = bytes([(size >> 21) & 0x7F, (size >> 14) & 0x7F, (size >> 7) & 0x7F, size & 0x7F])
    frame = b"GEOB" + synchsafe + b"\x00\x00" + body
    tag_size = len(frame)
    header = b"ID3\x04\x00\x00" + bytes(
        [(tag_size >> 21) & 0x7F, (tag_size >> 14) & 0x7F, (tag_size >> 7) & 0x7F, tag_size & 0x7F]
    )
    path.write_bytes(header + frame + b"\xff\xfb\x90\x00" + b"\x00" * 64)


def test_the_manifest_is_read_from_a_tiff_a_wav_an_mp4_and_an_mp3(tmp_path: Path):
    built = {
        "frame.dng": (_tiff_with, "tag 52545"),
        "take.wav": (_wav_with, "C2PA chunk"),
        "clip.mp4": (_mp4_with, "uuid box"),
        "track.mp3": (_mp3_with, "GEOB frame"),
    }
    for name, (build, where) in built.items():
        path = tmp_path / name
        build(path, _manifest(GENERATED_CLAIM))

        origin = read_c2pa_manifest(path)

        assert origin is not None, name
        assert origin.tool == "OpenAI Media Service API (gpt-image 2.0)", name
        assert origin.where == {"object": where}, name


def test_a_container_without_a_manifest_says_nothing(tmp_path: Path):
    path = tmp_path / "take.wav"
    _wav_with(path, b"")
    path.write_bytes(path.read_bytes().replace(b"C2PA", b"JUNK"))

    assert read_c2pa_manifest(path) is None
