"""C2PA Content Credentials.

A C2PA manifest is provenance the file carries about itself: which application
produced it, when, and - increasingly the point - whether it was generated by a
model rather than captured by a camera. It is the strongest account a file can
give of itself, and unlike a browser record it survives every copy.

The manifest lives in a JUMBF box (ISO/IEC 19566-5) holding CBOR, embedded in a
PNG `caBX` chunk or a JPEG APP11 segment. An SVG is not a binary container, so it
carries the same box as base64 inside a `c2pa:manifest` element. All of them are
walked here with the standard library, so the tool keeps no runtime dependencies.

**The signature is not verified.** Doing that needs certificate-chain validation
and a crypto library. Everything reported from here is therefore what the
manifest *claims*, and a manifest can be copied onto an unrelated file. It is
recorded as evidence, not as proof, and the report says which of the two it is.
"""

from __future__ import annotations

import base64
import binascii
import hashlib
import mmap
import re
import struct
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING, Any, BinaryIO

from ..cbor import CborError, loads
from ..models import EvidenceRecord
from .embedded.exif import TIFF_SUFFIXES, WEBP_SUFFIXES
from .embedded.isobmff import SUFFIXES as BMFF_SUFFIXES
from .embedded.riff import SUFFIXES as RIFF_SUFFIXES

if TYPE_CHECKING:  # `hashlib._Hash` exists in the type stubs, not at runtime.
    from hashlib import _Hash

PNG_SUFFIXES = {".png"}
JPEG_SUFFIXES = {".jpg", ".jpeg"}
ID3_SUFFIXES = {".mp3"}
SVG_SUFFIXES = {".svg"}
SUPPORTED_SUFFIXES = (
    PNG_SUFFIXES
    | SVG_SUFFIXES
    | JPEG_SUFFIXES
    | TIFF_SUFFIXES
    | WEBP_SUFFIXES
    | RIFF_SUFFIXES
    | BMFF_SUFFIXES
    | ID3_SUFFIXES
)

_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
_PNG_C2PA_CHUNK = b"caBX"
_JPEG_APP11 = 0xEB
#: Where each container keeps the manifest store, as c2pa-rs writes it.
_TIFF_C2PA_TAG = 0xCD41
_RIFF_C2PA_CHUNK = b"C2PA"
_BMFF_C2PA_UUID = bytes.fromhex("d8fec3d61b0e483c92975828877ec481")
_ID3_C2PA_MIME = (b"application/x-c2pa-manifest-store", b"application/c2pa")
_MAX_IFDS = 64
_MAX_ENTRIES = 4096
_MAX_BOXES = 4096
_MAX_STORE = 64 * 1024 * 1024

_JUMBF_SUPERBOX = b"jumb"
_JUMBF_DESCRIPTION = b"jumd"
_JUMBF_CBOR = b"cbor"

#: The hard binding: a hash over the asset with the manifest's own bytes cut
#: out of it. Checking it needs no key and no trust list - only the file - and
#: it answers a different question from the signature: not "who says so" but
#: "is this manifest even about these bytes".
_DATA_HASH = "c2pa.hash.data"

#: Claim boxes are labelled by version - `c2pa.claim`, `c2pa.claim.v2` - and
#: the claim is where the assertion's hash algorithm is inherited from when the
#: assertion itself leaves it out, which real manifests routinely do.
_CLAIM_PREFIX = "c2pa.claim"

#: Ingredient assertions are labelled `c2pa.ingredient`, `.v2`, `.v3`, and a
#: manifest with several of them numbers the labels: `c2pa.ingredient__1`.
_INGREDIENT_PREFIX = "c2pa.ingredient"

#: A manifest store holds one superbox per manifest, each labelled with its
#: URN. The last one is the active manifest - the one describing the file as
#: it is now - and earlier ones are the history it was built on.
_MANIFEST_LABEL = "urn:"

_MAX_ACTIONS = 32
_MAX_INGREDIENTS = 16

_HASHES = {"sha256": hashlib.sha256, "sha384": hashlib.sha384, "sha512": hashlib.sha512}

#: A megabyte at a time, so a large asset is never held in memory to hash it.
_CHUNK = 1 << 20

_MAX_BOXES = 4096
_MAX_DEPTH = 12

#: IPTC digital source types, mapped to what they mean for a reader.
_SOURCE_TYPES = {
    "trainedAlgorithmicMedia": "generated by an AI model",
    "compositeWithTrainedAlgorithmicMedia": "partly generated by an AI model",
    "algorithmicMedia": "generated by an algorithm",
    "digitalCapture": "captured by a camera",
    "digitalArt": "digital art",
    "composite": "a composite of several sources",
}


def read_c2pa_manifest(path: Path) -> EvidenceRecord | None:
    """Return what a C2PA manifest claims about the file, if one is present."""
    if path.suffix.lower() not in SUPPORTED_SUFFIXES:
        return None
    try:
        jumbf, where = _extract_jumbf(path)
    except (OSError, struct.error, ValueError):
        return None
    if not jumbf:
        return None

    payloads: list[tuple[str | None, dict[str, Any], int]] = []
    try:
        _walk(jumbf, 0, len(jumbf), 0, payloads)
    except (CborError, struct.error, ValueError):
        return None
    if not payloads:
        return None

    # Only the active manifest is summarised. An earlier manifest's generator
    # would describe an ingredient, not this file.
    manifests = sorted({index for _, _, index in payloads})
    active = [(label, payload) for label, payload, index in payloads if index == manifests[-1]]

    inherited = None
    for label, payload in active:
        if label and label.startswith(_CLAIM_PREFIX):
            inherited = payload.get("alg")
            break

    binding = None
    for label, payload in active:
        if label == _DATA_HASH:
            binding = _binding(path, payload, inherited)
            break

    record = _summarise(active, binding, len(manifests))
    if record is not None:
        record.where = {"object": where}
    return record


# --- container extraction ----------------------------------------------------


def _extract_jumbf(path: Path) -> tuple[bytes, str]:
    """The manifest store and the name of the structure it was read from."""
    if path.suffix.lower() in SVG_SUFFIXES:
        return _svg_element(path), "c2pa:manifest element"
    with path.open("rb") as handle:
        magic = handle.read(12)
        handle.seek(0)
        if magic.startswith(_PNG_MAGIC):
            return _png_chunk(handle), "caBX chunk"
        if magic.startswith(b"\xff\xd8"):
            return _jpeg_app11(handle), "APP11 segments"
        if magic[:4] in (b"II*\x00", b"MM\x00*"):
            return _tiff_tag(handle), f"tag {_TIFF_C2PA_TAG}"
        if magic.startswith(b"RIFF"):
            return _riff_chunk(handle), "C2PA chunk"
        if magic.startswith(b"ID3"):
            return _id3_frame(handle), "GEOB frame"
        if magic[4:8] in (b"ftyp", b"moov", b"mdat", b"free", b"skip", b"wide", b"uuid"):
            return _bmff_box(handle), "uuid box"
    return b"", ""


def _tiff_tag(handle: BinaryIO) -> bytes:
    """Tag 52545 in any directory of the chain, typed UNDEFINED or BYTE."""
    with mmap.mmap(handle.fileno(), 0, access=mmap.ACCESS_READ) as data:
        endian = ">" if data[:2] == b"MM" else "<"
        (offset,) = struct.unpack_from(endian + "I", data, 4)
        seen: set[int] = set()
        for _ in range(_MAX_IFDS):
            if offset in seen or offset <= 0 or offset + 2 > len(data):
                return b""
            seen.add(offset)
            (count,) = struct.unpack_from(endian + "H", data, offset)
            for index in range(min(count, _MAX_ENTRIES)):
                entry = offset + 2 + index * 12
                if entry + 12 > len(data):
                    return b""
                tag, kind, length, at = struct.unpack_from(endian + "HHII", data, entry)
                if tag == _TIFF_C2PA_TAG and kind in (1, 7) and 0 < length <= _MAX_STORE:
                    if length <= 4:
                        return bytes(data[entry + 8 : entry + 8 + length])
                    if at + length > len(data):
                        return b""
                    return bytes(data[at : at + length])
            after = offset + 2 + min(count, _MAX_ENTRIES) * 12
            if after + 4 > len(data):
                return b""
            (offset,) = struct.unpack_from(endian + "I", data, after)
    return b""


def _riff_chunk(handle: BinaryIO) -> bytes:
    """The `C2PA` chunk, a direct child of the RIFF chunk."""
    handle.seek(12)
    for _ in range(_MAX_BOXES):
        header = handle.read(8)
        if len(header) < 8:
            return b""
        name, size = struct.unpack("<4sI", header)
        if name == _RIFF_C2PA_CHUNK:
            return handle.read(size) if size <= _MAX_STORE else b""
        handle.seek(size + (size & 1), 1)
    return b""


def _bmff_box(handle: BinaryIO) -> bytes:
    """The top-level `uuid` box with the C2PA uuid: version and flags, a
    purpose, the offset of the first auxiliary box, then the store."""
    handle.seek(0, 2)
    end = handle.tell()
    at = 0
    for _ in range(_MAX_BOXES):
        if at + 8 > end:
            return b""
        handle.seek(at)
        size, name = struct.unpack(">I4s", handle.read(8))
        header = 8
        if size == 1:
            (size,) = struct.unpack(">Q", handle.read(8))
            header = 16
        elif size == 0:
            size = end - at
        if size < header:
            return b""
        if name == b"uuid" and size - header >= 16 + 4 + 1 + 8:
            if handle.read(16) == _BMFF_C2PA_UUID:
                body = handle.read(min(size - header - 16, _MAX_STORE))
                purpose_end = body.find(b"\x00", 4)
                if purpose_end < 0:
                    return b""
                return body[purpose_end + 1 + 8 :]
        at += size
    return b""


def _id3_frame(handle: BinaryIO) -> bytes:
    """The GEOB frame whose object is a manifest store, in ID3v2.3 or v2.4."""
    header = handle.read(10)
    if len(header) < 10 or header[3] not in (3, 4):
        return b""
    major = header[3]
    size = _synchsafe(header[6:10])
    body = handle.read(min(size, _MAX_STORE))
    at = 0
    for _ in range(_MAX_BOXES):
        if at + 10 > len(body) or body[at : at + 4] == b"\x00\x00\x00\x00":
            return b""
        name = body[at : at + 4]
        length = (
            _synchsafe(body[at + 4 : at + 8])
            if major == 4
            else struct.unpack(">I", body[at + 4 : at + 8])[0]
        )
        frame = body[at + 10 : at + 10 + length]
        at += 10 + length
        if name != b"GEOB" or not frame:
            continue
        encoding = frame[0]
        mime_end = frame.find(b"\x00", 1)
        if mime_end < 0 or frame[1:mime_end] not in _ID3_C2PA_MIME:
            continue
        rest = frame[mime_end + 1 :]
        terminator = b"\x00\x00" if encoding in (1, 2) else b"\x00"
        for _text in range(2):  # the file name, then the description
            cut = rest.find(terminator)
            if cut < 0:
                return b""
            rest = rest[cut + len(terminator) :]
        return rest
    return b""


def _synchsafe(raw: bytes) -> int:
    return (raw[0] << 21) | (raw[1] << 14) | (raw[2] << 7) | raw[3]


#: The element an SVG carries its manifest in. The prefix is the document's
#: choice, so the local name is what is matched, and the payload is base64 with
#: whatever whitespace the writer wrapped it at.
_SVG_MANIFEST = re.compile(
    rb"<(?:[A-Za-z0-9_.-]+:)?manifest\b[^>]*>(?P<payload>[A-Za-z0-9+/=\s]*)"
    rb"</(?:[A-Za-z0-9_.-]+:)?manifest\s*>",
    re.IGNORECASE,
)


def _svg_element(path: Path) -> bytes:
    """The manifest store an SVG writes as base64, decoded back to its bytes.

    The element is found in the bytes rather than by parsing the document: a
    drawing that will not parse can still carry a manifest, and nothing here
    needs the rest of the tree.
    """
    raw = path.read_bytes()[:_MAX_STORE]
    found = _SVG_MANIFEST.search(raw)
    if found is None:
        return b""
    try:
        return base64.b64decode(found.group("payload"))
    except (binascii.Error, ValueError):
        return b""


def _png_chunk(handle: BinaryIO) -> bytes:
    handle.seek(len(_PNG_MAGIC))
    while True:
        header = handle.read(8)
        if len(header) < 8:
            return b""
        length, chunk_type = struct.unpack(">I4s", header)
        if chunk_type == _PNG_C2PA_CHUNK:
            return handle.read(length)
        if chunk_type in (b"IDAT", b"IEND"):
            return b""
        handle.seek(length + 4, 1)  # payload plus CRC


def _jpeg_app11(handle: BinaryIO) -> bytes:
    """Collect APP11 segments, which carry the manifest split across markers."""
    handle.seek(2)
    parts: list[bytes] = []
    while True:
        marker = handle.read(2)
        if len(marker) < 2 or marker[0] != 0xFF:
            break
        if marker[1] in (0xDA, 0xD9):
            break
        length_bytes = handle.read(2)
        if len(length_bytes) < 2:
            break
        (length,) = struct.unpack(">H", length_bytes)
        payload = handle.read(length - 2)
        # APP11: 'JP', 2-byte box instance, 4-byte packet sequence, then data.
        if marker[1] == _JPEG_APP11 and payload.startswith(b"JP"):
            parts.append(payload[8:])
    return b"".join(parts)


# --- JUMBF ------------------------------------------------------------------


def _walk(
    data: bytes,
    offset: int,
    end: int,
    depth: int,
    found: list[tuple[str | None, dict[str, Any], int]],
    manifest: int = 0,
) -> None:
    """Collect every decodable CBOR payload, under the label it was filed as.

    A JUMBF superbox describes itself in a `jumd` box before its content, so a
    payload's label is whatever the last description at this level said. That
    is what tells an assertion apart from the claim, and one assertion apart
    from another - which matters here, because only one of them is the hash
    binding and reading it out by shape would be a guess.
    """
    if depth > _MAX_DEPTH:
        return

    label: str | None = None
    boxes = 0
    while offset + 8 <= end and boxes < _MAX_BOXES:
        boxes += 1
        (length,) = struct.unpack(">I", data[offset : offset + 4])
        box_type = data[offset + 4 : offset + 8]
        body = offset + 8

        if length == 0:
            length = end - offset
        elif length == 1:  # extended 64-bit length
            if body + 8 > end:
                return
            (length,) = struct.unpack(">Q", data[body : body + 8])
            body += 8
        if length < 8 or offset + length > end:
            return

        box_end = offset + length
        if box_type == _JUMBF_SUPERBOX:
            _walk(data, body, box_end, depth + 1, found, manifest)
        elif box_type == _JUMBF_DESCRIPTION:
            label = _label(data, body, box_end) or label
            if label and label.startswith(_MANIFEST_LABEL):
                manifest = max(index for _, _, index in found) + 1 if found else 1
        elif box_type == _JUMBF_CBOR:
            try:
                value = loads(data[body:box_end])
            except CborError:
                value = None
            if isinstance(value, dict):
                found.append((label, value, manifest))
        else:
            pass  # binary payloads: icons, thumbnails, signatures

        offset = box_end


def _label(data: bytes, offset: int, end: int) -> str | None:
    """The label out of a JUMBF description box, where it carries one.

    Sixteen bytes of type UUID, then a byte of toggles whose second bit says
    whether a null-terminated label follows.
    """
    if end - offset < 17 or not data[offset + 16] & 0x02:
        return None
    raw = data[offset + 17 : end]
    stop = raw.find(b"\x00")
    return raw[: stop if stop >= 0 else len(raw)].decode("utf-8", "replace") or None


# --- the hard binding -------------------------------------------------------


def _binding(path: Path, assertion: dict[str, Any], inherited: object = None) -> str | None:
    """Whether the manifest's own hash still describes the file it sits in.

    This is not the signature. It says nothing about who produced the manifest
    or whether to believe them; it says whether this manifest is about these
    bytes at all. A manifest lifted onto a different image fails here, and so
    does an asset edited after the manifest was written - and both are worth
    knowing without a certificate in sight.
    """
    recorded = assertion.get("hash")
    named = assertion.get("alg") or inherited
    hasher = _HASHES.get(named if isinstance(named, str) else "")
    if not isinstance(recorded, bytes) or not recorded or hasher is None:
        return None  # nothing to compare, or an algorithm this cannot compute

    exclusions = assertion.get("exclusions")
    spans = _spans(exclusions) if exclusions is not None else []
    if spans is None:
        return None

    try:
        computed = _hash_excluding(path, spans, hasher)
    except OSError:
        return None
    if computed is None:
        return None
    return "hash binding matches" if computed == recorded else "hash binding does not match"


def _spans(exclusions: object) -> list[tuple[int, int]] | None:
    """The excluded byte ranges, or None where they cannot be trusted."""
    if not isinstance(exclusions, list):
        return None
    spans: list[tuple[int, int]] = []
    for item in exclusions:
        if not isinstance(item, dict):
            return None
        start, length = item.get("start"), item.get("length")
        if not isinstance(start, int) or not isinstance(length, int):
            return None
        if isinstance(start, bool) or isinstance(length, bool):
            return None
        if start < 0 or length < 0:
            return None
        spans.append((start, start + length))
    spans.sort()
    for (_, first_end), (second_start, _) in zip(spans, spans[1:], strict=False):
        if second_start < first_end:
            return None  # overlapping ranges: the intended coverage is unclear
    return spans


def _hash_excluding(
    path: Path, spans: list[tuple[int, int]], hasher: Callable[[], _Hash]
) -> bytes | None:
    """Hash the file with those byte ranges left out of it."""
    digest = hasher()
    position = 0
    with path.open("rb") as handle:
        for start, stop in spans:
            if start < position:
                return None
            _feed(handle, digest, start - position)
            handle.seek(stop)
            position = stop
        while chunk := handle.read(_CHUNK):
            digest.update(chunk)
    return digest.digest()


def _feed(handle: BinaryIO, digest: _Hash, count: int) -> None:
    while count > 0:
        chunk = handle.read(min(count, _CHUNK))
        if not chunk:
            return
        digest.update(chunk)
        count -= len(chunk)


# --- interpretation ----------------------------------------------------------


def _summarise(
    payloads: list[tuple[str | None, dict[str, Any]]],
    binding: str | None = None,
    manifests: int = 1,
) -> EvidenceRecord | None:
    generator = None
    software = None
    when = None
    source_type = None
    source_uri = None
    actions: list[str] = []
    ingredients: list[dict[str, str]] = []

    for label, claim in payloads:
        generator = generator or _generator_name(claim)
        if label and label.split("__", 1)[0].startswith(_INGREDIENT_PREFIX):
            if len(ingredients) < _MAX_INGREDIENTS and (ingredient := _ingredient(claim)):
                ingredients.append(ingredient)
            continue
        for action in _actions(claim):
            if (name := _string(action.get("action"))) and len(actions) < _MAX_ACTIONS:
                actions.append(name)
            when = when or _string(action.get("when"))
            # The label and the value it was read from come from one action,
            # so the field never names a different source type than the note.
            if source_type is None and (named := _source_label(action.get("digitalSourceType"))):
                source_type, source_uri = named, _string(action.get("digitalSourceType"))
            software = software or _software_agent(action.get("softwareAgent"))

    tool = generator or software
    if generator and software and software not in generator:
        tool = f"{generator} ({software})"
    if not tool and not when and not source_type and not ingredients:
        return None

    parents = [item.get("title") for item in ingredients if item.get("relationship") == "parentOf"]
    lineage = None
    if parents:
        lineage = f"derived from {parents[0]}" if parents[0] else "derived from an ingredient"
    history = f"{manifests} manifests" if manifests > 1 else None
    notes = [
        note for note in (source_type, lineage, history, binding, "signature not verified") if note
    ]
    # Under the manifest's own names, so what the claim said can be checked
    # without reading it back out of a sentence.
    fields = {
        name: value
        for name, value in (
            ("claim_generator", generator),
            ("softwareAgent", software),
            ("digitalSourceType", source_uri),
        )
        if value
    }
    if actions:
        fields["actions"] = ", ".join(actions)
    if manifests > 1:
        fields["manifests"] = str(manifests)
    if ingredients:
        fields["ingredients"] = str(len(ingredients))
        for index, ingredient in enumerate(ingredients, 1):
            for name, value in ingredient.items():
                fields[f"Ingredient[{index}]:{name}"] = value
    return EvidenceRecord(
        source="c2pa", block="c2pa", tool=tool, at=when, note="; ".join(notes), fields=fields
    )


def _ingredient(assertion: dict[str, Any]) -> dict[str, str] | None:
    """What an ingredient assertion says about the asset it was built from.

    Version 1 spells the identifiers `document_id` and `instance_id`; later
    versions drop the underscore and make the title optional. Either way, an
    ingredient that carries its own manifest is a step in the provenance chain
    and one that does not is a plain file the generator opened.
    """
    found: dict[str, str] = {}
    for name in ("title", "format", "relationship"):
        if text := _string(assertion.get(name)):
            found[name] = text
    for name, spelled in (
        ("document_id", "documentID"),
        ("documentID", "documentID"),
        ("instance_id", "instanceID"),
        ("instanceID", "instanceID"),
    ):
        if spelled not in found and (text := _string(assertion.get(name))):
            found[spelled] = text
    if any(key in assertion for key in ("c2pa_manifest", "activeManifest", "claim_signature")):
        found["manifest"] = "own manifest"
    return found or None


def _generator_name(claim: dict[str, Any]) -> str | None:
    info = claim.get("claim_generator_info")
    if isinstance(info, dict):
        name = _string(info.get("name"))
        version = _string(info.get("version"))
        if name:
            return f"{name} {version}".strip() if version else name
    if isinstance(info, list):
        for entry in info:
            if isinstance(entry, dict) and _string(entry.get("name")):
                return _string(entry["name"])
    return _string(claim.get("claim_generator"))


def _actions(claim: dict[str, Any]) -> list[dict[str, Any]]:
    actions = claim.get("actions")
    if isinstance(actions, list):
        return [item for item in actions if isinstance(item, dict)]
    return []


def _software_agent(value: object) -> str | None:
    if isinstance(value, dict):
        name = _string(value.get("name"))
        version = _string(value.get("version"))
        if name:
            return f"{name} {version}".strip() if version else name
        return None
    return _string(value)


def _source_label(value: object) -> str | None:
    text = _string(value)
    if not text:
        return None
    return _SOURCE_TYPES.get(text.rstrip("/").rsplit("/", 1)[-1])


def _string(value: object) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None
