"""What a scan amounts to, before anybody lays it out.

A scan is a list of records. A case is what they add up to: which files to open
first, what the records establish when read together, where two of them
contradict each other, what this machine could have told and could not, and
which values lead somewhere else. Every rendering of a case states the same
things because it reads them here, and none of them decides what is true.

Nothing here goes beyond what a record says. A finding is a count or a
coincidence the records themselves state - two files stamped at the same
second, one serial in three photographs - and never a guess at who or why.
"""

from __future__ import annotations

import hashlib
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .cluster import AUTHOR, DEVICE, LENS, cluster
from .correlate import ATTRIBUTION_CONFLICT, CONFLICTS, CorrelationResult, correlate, instant
from .correlate import Finding as Correlated
from .doctor import ARTIFACT, AVAILABLE, HOME_SOURCES, PARTIAL, UNAVAILABLE, Survey
from .identify import Identifier
from .models import BLOCK_LABELS, CATEGORIES, METADATA, EvidenceRecord, FileRecord, category, label

#: Where a file stands: something to look at again, something found, nothing found.
REVIEW = "review"
EVIDENCE = "evidence"
NOTHING = "nothing"
_RANK = {REVIEW: 0, EVIDENCE: 1, NOTHING: 2}

#: The IPTC digital source types that say a model made the picture.
_GENERATED = {
    "trainedAlgorithmicMedia": "generated by an AI model",
    "compositeWithTrainedAlgorithmicMedia": "partly generated by an AI model",
}

#: Moments written by default rather than by anybody: the Unix and DOS epochs.
#: Every file carrying one would be one cluster, and a meaningless one.
_PLACEHOLDER_MOMENTS = frozenset({"1970-01-01T00:00:00Z", "1980-01-01T00:00:00Z"})

#: The fewest files one author has to be named in before it is a finding. Two
#: documents by one person is a folder; three is a pattern worth a line.
SHARED_AUTHOR = 3

#: A file holding this many identifiers is a list, and is folded into one entry.
DENSE = 50

#: How many identifiers found in more than one file are named one by one.
SHARED_PIVOTS = 8

#: Every store a scan reads out of a home directory. Any other artifact check
#: is an attribute a file may carry, which can be readable and still be absent.
_STORES = frozenset(name for names in HOME_SOURCES.values() for name in names)


@dataclass(slots=True)
class CaseFile:
    """One scanned file, its number in this report, and what concerns it."""

    ref: str
    record: FileRecord
    state: str

    #: What was read under each category, by the name the report uses.
    found: dict[str, list[str]]
    findings: list[str] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)
    pivots: list[str] = field(default_factory=list)


@dataclass(slots=True)
class Item:
    """One file a finding is about, and what the finding says of it alone."""

    path: str
    facts: list[tuple[str, str]] = field(default_factory=list)


@dataclass(slots=True)
class Finding:
    ref: str
    kind: str
    title: str

    #: Whether it wants a second look, rather than being worth knowing.
    notable: bool
    facts: list[tuple[str, str]]
    items: list[Item]

    #: The section that holds the rest of it, where there is one.
    see: str | None = None


@dataclass(slots=True)
class Difference:
    """One field two sources state differently, with both statements."""

    field: str
    kind: str
    values: list[tuple[str, str]]

    #: How far the second moment is from the first, where both are moments.
    delta: str | None = None


@dataclass(slots=True)
class Conflict:
    ref: str
    path: str
    sources: list[str]
    differences: list[Difference]


@dataclass(slots=True)
class Source:
    """One place this machine keeps traces, and whether it could be read."""

    name: str

    #: `found`, `readable`, `partial`, `not found`, `not readable` or
    #: `not supported`. A store is found; an attribute is readable, because
    #: being able to read it says nothing about whether any file carries it.
    state: str
    detail: str
    since: str | None = None
    store: bool = True


@dataclass(slots=True)
class Dense:
    """A file that holds more identifiers than a reader can take one by one."""

    path: str
    places: int
    by_type: list[tuple[str, int]]


@dataclass(slots=True)
class Pivots:
    total: int

    #: How many were found in more than one file; `shared` names the first few.
    across: int
    shared: list[tuple[str, Identifier]]
    cross_corpus: int
    by_type: list[tuple[str, int]]
    dense: list[Dense]


@dataclass(slots=True)
class Case:
    root: Path
    files: list[CaseFile]
    findings: list[Finding]
    conflicts: list[Conflict]
    coverage: list[Source]

    #: The oldest record any trace store holds. A file that arrived before it
    #: cannot be matched to them, whatever the rest of the report says.
    begins: str | None
    relationships: int
    pivots: Pivots | None


def analyse(
    records: list[FileRecord],
    root: Path,
    *,
    survey: Survey | None = None,
    identifiers: list[Identifier] | None = None,
) -> Case:
    """Read a scan as a case. `survey` and `identifiers` add what they cover."""
    verdicts = {record.path: correlate(record) for record in records}
    files = _files(records, verdicts)
    by_path = {entry.record.path: entry for entry in files}

    conflicts = _conflicts(files, verdicts)
    for conflict in conflicts:
        by_path[conflict.path].conflicts.append(conflict.ref)

    findings = _findings(files, records, conflicts)
    for finding in findings:
        for item in finding.items:
            if finding.ref not in by_path[item.path].findings:
                by_path[item.path].findings.append(finding.ref)

    pivots = None
    if identifiers is not None:
        pivots = _pivots(identifiers, files)
        for entry in identifiers:
            for path in entry.holders:
                held = by_path.get(path)
                if held is not None and entry.type not in held.pivots:
                    held.pivots.append(entry.type)

    coverage, begins = _coverage(survey)
    return Case(
        root=root,
        files=files,
        findings=findings,
        conflicts=conflicts,
        coverage=coverage,
        begins=begins,
        relationships=sum(len(record.links) for record in records),
        pivots=pivots,
    )


def named(found: EvidenceRecord) -> str:
    """What to call the source of a record: its block where it came from one."""
    if found.block and found.block in BLOCK_LABELS:
        return BLOCK_LABELS[found.block]
    if found.source == "browser-download" and found.tool:
        return f"{found.tool.capitalize()} download"
    return label(found)


# --- files ---------------------------------------------------------------------


def _files(records: list[FileRecord], verdicts: dict[str, CorrelationResult]) -> list[CaseFile]:
    """Numbered in the order to open them: what wants a second look, then what
    was explained, largest first, then what nothing was found for."""

    def state(record: FileRecord) -> str:
        if not record.evidence:
            return NOTHING
        return REVIEW if verdicts[record.path].contested else EVIDENCE

    ordered = sorted(records, key=lambda r: (_RANK[state(r)], -r.size, r.path))
    width = max(3, len(str(len(records))))
    return [
        CaseFile(f"#{number:0{width}d}", record, state(record), _found(record))
        for number, record in enumerate(ordered, 1)
    ]


def _found(record: FileRecord) -> dict[str, list[str]]:
    said: dict[str, list[str]] = {name: [] for name in CATEGORIES}
    for found in record.evidence:
        bucket = said[category(found)]
        if (name := named(found)) not in bucket:
            bucket.append(name)
    return said


# --- conflicts -----------------------------------------------------------------


def _conflicts(files: list[CaseFile], verdicts: dict[str, CorrelationResult]) -> list[Conflict]:
    made: list[Conflict] = []
    for entry in files:
        contested = [f for f in verdicts[entry.record.path].findings if f.kind in CONFLICTS]
        if not contested:
            continue
        sources = list(dict.fromkeys(name for f in contested for name in f.sources or () if name))
        made.append(
            Conflict(
                ref=f"C{len(made) + 1:02d}",
                path=entry.record.path,
                sources=sources,
                differences=[_difference(f) for f in contested],
            )
        )
    return made


def _difference(found: Correlated) -> Difference:
    name = found.field or found.kind.replace("_", " ")
    if not (found.values and found.sources):
        return Difference(name, found.kind, [("", found.text)])
    left, right = found.values
    # Where one block states both values it names both sides, and `PDF Info is
    # two hours earlier than PDF Info` tells a reader nothing. Which of its two
    # fields is the earlier one is the whole content of the finding, so the
    # sides take their own names wherever the finding carries them.
    named = found.fields or found.sources
    (left_source, right_source) = (named[0] or "", named[1] or "")
    first, second = instant(left), instant(right)
    if first is None or second is None:
        return Difference(name, found.kind, [(left_source, left), (right_source, right)])
    return Difference(
        name,
        found.kind,
        [(left_source, _clock(*first)), (right_source, _clock(*second))],
        _apart(first[0], second[0]),
    )


def _clock(moment: datetime, zoned: bool) -> str:
    """A moment as a reader reads it, saying UTC only where the writer gave a zone."""
    return moment.strftime("%Y-%m-%d %H:%M:%S") + (" UTC" if zoned else "")


def _apart(first: datetime, second: datetime) -> str | None:
    """`72 days earlier`: where the second moment stands against the first."""
    seconds = (second - first).total_seconds()
    if not seconds:
        return None
    word = "later" if seconds > 0 else "earlier"
    seconds = abs(seconds)
    days = seconds / 86400
    if seconds < 60:
        said = _count(round(seconds), "second")
    elif seconds < 3600:
        said = _count(round(seconds / 60), "minute")
    elif seconds < 86400:
        said = _count(round(seconds / 3600), "hour")
    elif days < 365:
        said = _count(round(days), "day")
    else:
        years = int(days // 365.2425)
        months = round((days - years * 365.2425) / 30.436875)
        if months == 12:
            years, months = years + 1, 0
        said = _count(years, "year") + (f" {_count(months, 'month')}" if months else "")
    return f"{said} {word}"


def _count(number: int, noun: str) -> str:
    return f"{number} {noun}" if number == 1 else f"{number} {noun}s"


# --- findings ------------------------------------------------------------------


def _findings(
    files: list[CaseFile], records: list[FileRecord], conflicts: list[Conflict]
) -> list[Finding]:
    """What the records establish read together, the ones to act on first."""
    ordered = [entry.record for entry in files]
    position = {record.path: number for number, record in enumerate(ordered)}
    made: list[Finding] = []

    def add(
        kind: str,
        title: str,
        notable: bool,
        facts: list[tuple[str, str]],
        items: list[Item],
        see: str | None = None,
    ) -> None:
        made.append(Finding(f"F{len(made) + 1:02d}", kind, title, notable, facts, items, see))

    generated = [item for record in ordered if (item := _generated(record))]
    if generated:
        add(
            "generated",
            "Declared AI-generated source",
            True,
            [("files", str(len(generated)))],
            generated,
        )

    misnamed = [item for record in ordered if (item := _misnamed(record))]
    if misnamed:
        add(
            "signature",
            "Extension does not match content",
            True,
            [("files", str(len(misnamed)))],
            misnamed,
        )

    if conflicts:
        metadata_only = all(
            difference.kind == ATTRIBUTION_CONFLICT
            for conflict in conflicts
            for difference in conflict.differences
        )
        add(
            "conflicts",
            "Metadata conflicts" if metadata_only else "Conflicting evidence",
            True,
            [("files", str(len(conflicts)))],
            [Item(conflict.path) for conflict in conflicts],
            see="CONFLICTS",
        )

    stamped: dict[str, list[FileRecord]] = defaultdict(list)
    for record in ordered:
        moments = (
            found.at
            for found in record.evidence
            if found.at and category(found) == METADATA and found.at not in _PLACEHOLDER_MOMENTS
        )
        for moment in dict.fromkeys(moments):
            stamped[moment].append(record)
    for moment, stamped_files in sorted(stamped.items(), key=lambda pair: (-len(pair[1]), pair[0])):
        if len(stamped_files) < 2:
            continue
        facts = [("timestamp", stamp(moment)), ("files", str(len(stamped_files)))]
        same = _same_bytes(stamped_files)
        if same is not None:
            facts.append(("bytes", "identical" if same else "different"))
        add(
            "same-second",
            "Same-second creation cluster",
            False,
            facts,
            [Item(record.path) for record in stamped_files],
        )

    groups = cluster(records)
    for group in groups:
        if group.axis == AUTHOR and len(group.paths) >= SHARED_AUTHOR:
            add(
                "author",
                "Shared author",
                False,
                [
                    ("author", group.name),
                    ("files", str(len(group.paths))),
                    ("evidence", group.basis),
                ],
                [Item(path) for path in sorted(group.paths, key=position.__getitem__)],
            )
    for group in groups:
        if group.axis == DEVICE and len(group.paths) >= 2:
            add(
                "camera",
                "Shared camera body",
                False,
                [
                    ("serial", group.name),
                    ("files", str(len(group.paths))),
                    ("evidence", group.basis),
                ],
                [Item(path) for path in sorted(group.paths, key=position.__getitem__)],
            )
    for group in groups:
        # Reported apart from the body, and after it, because one lens on two
        # bodies is a true claim that the bodies were not the same.
        if group.axis == LENS and len(group.paths) >= 2:
            add(
                "lens",
                "Shared lens",
                False,
                [
                    ("serial", group.name),
                    ("files", str(len(group.paths))),
                    ("evidence", group.basis),
                ],
                [Item(path) for path in sorted(group.paths, key=position.__getitem__)],
            )

    located = [record for record in ordered if any(found.geo for found in record.evidence)]
    if located:
        add(
            "geo",
            "Geographic metadata exposure",
            False,
            [("files", str(len(located)))],
            [Item(record.path) for record in located],
        )

    bare = [record for record in ordered if not record.evidence]
    if bare:
        add(
            "no-trace",
            "No supporting trace found",
            False,
            [("files", f"{len(bare)} / {len(records)}")],
            [Item(record.path) for record in bare],
            see="EVIDENCE COVERAGE",
        )
    return made


def _generated(record: FileRecord) -> Item | None:
    """The file, if a manifest in it says a model made it."""
    for found in record.evidence:
        declared = str(found.fields.get("digitalSourceType") or "").rstrip("/").rsplit("/", 1)[-1]
        if declared not in _GENERATED:
            continue
        facts = [("evidence", named(found))]
        for key, name in (("claim_generator", "generator"), ("softwareAgent", "software agent")):
            if value := found.fields.get(key):
                facts.append((name, str(value)))
        facts.append(("source type", _GENERATED[declared]))
        # What the manifest says is not what this tool checked. The certificate
        # chain is never validated here, so the claim travels with that said.
        facts.append(("signature", "not verified"))
        return Item(record.path, facts)
    return None


def _misnamed(record: FileRecord) -> Item | None:
    """The file, if its own bytes are written in a format its name denies.

    The pair travels with the item. A finding that named only the files would
    leave a reader knowing that two of them are not what they are called, and
    not what either of them is.
    """
    for found in record.evidence:
        if found.source == "file-signature":
            return Item(
                record.path, [(name, found.fields[name]) for name in ("extension", "content")]
            )
    return None


def stamp(moment: str) -> str:
    try:
        parsed = datetime.fromisoformat(moment.replace("Z", "+00:00"))
    except ValueError:
        return moment
    if parsed.tzinfo is None:
        return parsed.strftime("%Y-%m-%d %H:%M:%S")
    return parsed.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _same_bytes(group: list[FileRecord]) -> bool | None:
    """Whether the files are one file copied, or None if that could not be read."""
    if len({record.size for record in group}) > 1:
        return False
    digests = set()
    for record in group:
        try:
            digests.add(record.sha256 or _digest(Path(record.path)))
        except OSError:
            return None
    return len(digests) == 1


def _digest(path: Path) -> str:
    hashed = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            hashed.update(chunk)
    return hashed.hexdigest()


# --- coverage ------------------------------------------------------------------


def _coverage(found: Survey | None) -> tuple[list[Source], str | None]:
    if found is None:
        return [], None
    reach = {
        check.name.split(" oldest")[0]: check.detail for check in found.horizon if check.detail
    }
    sources = []
    for check in found.checks:
        if check.kind != ARTIFACT:
            continue
        store = check.name in _STORES
        since = next((day for prefix, day in reach.items() if check.name.startswith(prefix)), None)
        sources.append(Source(check.name, _covered(check.state, store), check.detail, since, store))
    days = [source.since for source in sources if source.since]
    return sources, min(days) if days else None


def _covered(state: str, store: bool) -> str:
    if state == AVAILABLE:
        return "found" if store else "readable"
    if state == PARTIAL:
        return "partial"
    if state == UNAVAILABLE:
        return "not found" if store else "not readable"
    return "not supported"


# --- pivots --------------------------------------------------------------------


def _pivots(identifiers: list[Identifier], files: list[CaseFile]) -> Pivots:
    position = {entry.record.path: number for number, entry in enumerate(files)}
    shared = sorted(
        (entry for entry in identifiers if entry.files > 1),
        key=lambda entry: (-entry.files, -entry.count, entry.type, entry.normalized),
    )[:SHARED_PIVOTS]

    held: dict[str, Counter[str]] = defaultdict(Counter)
    for entry in identifiers:
        for path, times in entry.holders.items():
            held[path][entry.type] += times
    dense = [
        Dense(
            path, sum(kinds.values()), sorted(kinds.items(), key=lambda pair: (-pair[1], pair[0]))
        )
        for path, kinds in held.items()
        if sum(kinds.values()) >= DENSE
    ]
    dense.sort(key=lambda entry: (-entry.places, position.get(entry.path, 0)))

    return Pivots(
        total=len(identifiers),
        across=sum(1 for entry in identifiers if entry.files > 1),
        shared=[(f"P{number:02d}", entry) for number, entry in enumerate(shared, 1)],
        cross_corpus=sum(1 for entry in identifiers if len(entry.corpora) > 1),
        by_type=sorted(
            Counter(entry.type for entry in identifiers).items(),
            key=lambda pair: (-pair[1], pair[0]),
        ),
        dense=dense,
    )
